env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  logger: readable
rules:
  no-plusplus: 0
  import/prefer-default-export: 0
  import/extensions:
    - error
    - always
  no-console: 0
  arrow-body-style: 0
  prefer-destructuring: 0
  no-param-reassign: 0
  no-restricted-syntax: 0
  object-curly-newline: 0
